apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-k6-script
data:
  load.js: |
    import http from 'k6/http';
    import { sleep } from 'k6';

    export let options = {
      vus: {{ .Values.k6.vus }},
      duration: '{{ .Values.k6.duration }}',
    };

    export default function () {
      http.get('http://{{ .Values.nginx.ingress.host }}');
      sleep(1);
    }
