apiVersion: v1
kind: ConfigMap
metadata:
  name: tardis-code
  namespace: rodeo-lab-1
data:
  tardis.js: |
    const http = require('http');

    // Get maintenance mode status from the environment variable
    const maintenanceMode = process.env.MAINTENANCE_MODE === 'true';

    // Server logic
    const server = http.createServer((req, res) => {
      if (maintenanceMode) {
        console.log('Tardis is offline, Maintenance mode is active. Returning 503 Service Unavailable.');
        res.writeHead(503, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify({
          message: 'The server is currently in maintenance mode. Please try again later.',
        }));
      } else {
        console.log('Tardis is running normally and ready for time-travel. Processing request...');
        res.writeHead(200, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify({
          message: 'Application is running normally.',
        }));
      }
    });

    // Simulate a startup delay
    const PORT = 8080;
    console.log('Starting Tardis... Simulating startup delay (10 seconds).');
    console.log(`Tardis started. Listening on port ${PORT}.`);
    server.listen(PORT, () => console.log(`Open for time-traveling at http://0.0.0.0:${PORT}`));
  scenario.ts: |
    import http from 'k6/http';
    import { check, sleep } from 'k6';

    export let options = {
      vus: 1,
      stages: [
        { duration: '2m', target: 0 },
        { duration: '30s', target: 4 },
        { duration: '2h', target: 4 }, // long enough for lab to continue running.
      ],
    };

    export default function () {
      let res = http.get('http://tardis.rodeo-lab-1.svc.cluster.local:8080');
      check(res, { 'Tardis operational': (r) => r.status === 200 });
      sleep(1);
    }
