apiVersion: apps/v1
kind: Deployment
metadata:
  name: cool-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cool-server
  template:
    metadata:
      labels:
        app: cool-server
    spec:
      containers:
      - name: cool-server
        image: node:18
        command: ["node", "/app/cool-server.js"]
        env:
        - name: CACHE_MAX_SIZE
          value: "100" # Max cache size in MB (adjustable)
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: app-code
          mountPath: /app
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "64Mi"
            cpu: "200m"
      volumes:
      - name: app-code
        configMap:
          name: cool-server-code

