apiVersion: apps/v1
kind: Deployment
metadata:
  name: spiky
  namespace: rodeo-lab-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spiky
  template:
    metadata:
      labels:
        app: spiky
    spec:
      containers:
      - name: spiky
        image: node:18
        command: ["node", "/app/spiky-server.js"]
        env:
        - name: CACHE_MAX_SIZE
          value: "100" # Max cache size in MB (adjustable)
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: app-code
          mountPath: /app
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
      volumes:
      - name: app-code
        configMap:
          name: spiky-code

