apiVersion: batch/v1
kind: Job
metadata:
  name: cool-server-load-test
  namespace: observe-a-demo
spec:
  template:
    metadata:
      name: cool-server-load-test
    spec:
      containers:
      - name: k6
        image: grafana/k6:latest
        command: ["k6", "run", "/scripts/scenario.ts"]
        volumeMounts:
        - name: k6-script
          mountPath: /scripts
      restartPolicy: Never
      volumes:
      - name: k6-script
        configMap:
          name: cool-server-code
