apiVersion: v1
kind: ConfigMap
metadata:
  name: high-maintenance-config
  namespace: hands-on-labs
data:
  high-maintenance.js: |
    const maintenanceMode = process.env.MAINTENANCE_MODE === 'true';
    setTimeout(() => {
      if (maintenanceMode) {
        console.log('[ERROR]: Maintenance mode enabled. Exiting...');
        process.exit(0);
      } else {
        console.log('Application started. Running in normal mode...');

        // Simulate application doing some periodic work
        setInterval(() => {
          console.log('Application is processing tasks...');
        }, 5000);
      }
    }, 5000); // 10-second delay
