apiVersion: v1
kind: ConfigMap
metadata:
  name: high-maintenance-config
  namespace: hands-on-labs
data:
  high-maintenance.js: |
    const maintenanceMode = process.env.MAINTENANCE_MODE === 'true';

    if (maintenanceMode) {
      console.log('Maintenance mode enabled. Exiting...');
      process.exit(0);
    } else {
      console.log('Application started. Running in normal mode...');

      // Simulate some work
      setInterval(() => {
        console.log('Application is processing tasks...');
      }, 5000);
    }
